# EXERCICIO 05:

# DECLARANDO UMA VARIAVEL MUTAVEL (O VALOR PODE ALTERAR)
tentativas_maximas = 3

# DECLARANDO UMA CONSTANTE (O VALOR NÃO PODE ALTERAR, POR ISSO ELA É DECLARADA EM CAIXA ALTA)
TIMEOUT_CONEXAO = 30

# IMPRIMINDO ESSAS VARIAVEIS COM F-STRING
print(f"O limite de tentativas é de {tentativas_maximas} com timeout fixado em {TIMEOUT_CONEXAO} segundos!")