print(f"Preço: R$ {25.12345: .2f}")
# NESSE CASO, ELE VAI IMPRIMIR O ENUNCIADO PREÇO FORMATADO.

# COMO?
# O TEXTO JÁ ESTÁ NA F"STRING" E PÓS O VALOR, VOCÊ ESTÁ SOLICITANDO
# PARA ELE IMPRIMIR DUAS CASAS PÓS O PONTO (.2F)