# EXERCICIO 05:

# USANDO O PARAMETRO "SEP="
print("2026", "08", "16", sep="/")
# COLOQUEI A BARRA "/", DENTRO DO PARAMETRO PARA ELE COLOCAR ENTRE OS NUMEROS CITADOS

# O MECANISMO "END=""" SERVE PARA MOSTRAR AO CODIGO QUE VOCE REOMVER A QUEBRA DE LINHA PADRÃO
# E A SEGUNDA PRONUNCIA VENHA DEPOIS
print("Carregando sistema...", end="")
print(" [OK]")