# EXERCICIO 19: NEGAÇÕES E LÓGICA COMPOSTA

# SOLICITE A FAIXA DE IP AO COLABORADOR
faixa = input("Informe a faixa de IP: ")

# DEVEMOS EXECUTAR A VERIFICAÇÃO DUAS VEZES, PORQUE EM PYTHON, QUALQUER STRING NÃO VAZIA
# É VERDADEIRO, INDEPENDENTE SE A PRIMEIRA VERIFICAÇÃO FOSSE FALSE, A SEGUNDA SE TORNARIA VERDADEIRA
# MESMO COM INSERÇÃO DE QUALQUER VALOR

# SE FAIXA FOR IGUAL A "10.0.0" OU FAIXA FOR IGUAL A "192.168.1"
if (faixa == "10.0.0" or  faixa == "192.168.1"):# OPERADOR LÓGICO: OR E DUAS VERIFICAÇÕES
    print("Endereço IP pertencente ao bloco privado (Internal Network).") # CONDIÇÃO VERDADEIRA
else: # SENÃO
    print("Endereço IP público ou roteável na Internet.") # CONDIÇÃO FALSA