# EXERCICIO 05:

# PEÇA A TEMPERATURA EM CELSIUS E FAÇA O CASTING DE DADOS PARA FLOAT
C = float(input("Informe uma temperatura: "))

# FORMULA PARA CALCULAR UMA TEMPERATURA EM FAHRENHEIT
F = (C * 1.8) + 32

# IMPRIMA ESTÁ MENSAGEM COM A FORMATAÇÃO EM F-STRING
print(f"{C}°C equivalem a {F:.1f}°F")